namespace Zand.App.Scenarios;

using Zand.App.Config;
using Zand.Core.Ballistics;
using Zand.Core.CellularAutomata;
using Zand.Core.CellularAutomata.Algorithms;
using Zand.Core.CellularAutomata.Chunking;
using Zand.Core.Coupling;
using Zand.Rendering;

public record RunConfig(
    string ScenarioName,
    int RepeatIndex,
    int WorldWidth,
    int WorldHeight,
    CaAlgorithmType CaAlgorithm,
    RigidBodySimulationType RbSimulation,
    CouplingMode Coupling,
    LiquidPhysicsMode LiquidPhysics,
    GravityMode Gravity,
    TempBodyLifetime TempBodyLifetime,
    TempBodyMerging TempBodyMerging,
    ChunkSize ChunkSize,
    ActiveRectangle ActiveRectangleMode,
    ParallelismMode ParallelismMode,
    LiquidPressureMode LiquidPressureMode,
    SameTickMoveGuard SameTickMoveGuard,
    RowSweepOrder RowSweepOrder,
    CellRenderSmoothing CellRenderSmoothing,
    BallisticParticleMode BallisticParticleMode,
    EjectionResistanceMode EjectionResistanceMode,
    ParticleCollisionMode ParticleCollisionMode,
    LandingSearchMode LandingSearchMode,
    EjectionImpulseTargetMode EjectionImpulseTargetMode,
    EjectionDeflectionMode EjectionDeflectionMode,
    ReattachmentMode ReattachmentMode,
    RasterizationBodyParallelism RasterizationBodyParallelism,
    RasterizationCellParallelism RasterizationCellParallelism,
    BallisticResolutionParallelism BallisticResolutionParallelism,
    RenderParallelism RenderParallelism);
