<Project>

    <PropertyGroup Condition="'$(MSBuildProjectName)' != 'ChipmunkSharp'">
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>

    <PropertyGroup Condition="'$(MSBuildProjectName)' == 'ChipmunkSharp'">
        <NoWarn>$(NoWarn);CS0649;NETSDK1215</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="'$(MSBuildProjectName)' != 'ChipmunkSharp'">
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Condition="'$(MSBuildProjectName)' != 'ChipmunkSharp'">
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" Link="stylecop.json"/>
    </ItemGroup>

</Project>
